# Generated by Django 3.2.9 on 2021-12-26 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ridt_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('currency', models.CharField(default='RU', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('next_payment_date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('value', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('usage_count', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('trial_period', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('creation_time', 'mail')},
        ),
        migrations.AlterField(
            model_name='application',
            name='price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ridt_site.price'),
        ),
        migrations.AlterField(
            model_name='application',
            name='promo_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ridt_site.promocode'),
        ),
    ]
