# Generated by Django 3.2.9 on 2021-12-30 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridt_site', '0003_auto_20211226_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 13, 36, 17, 283110)),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_payment_date',
            field=models.DateField(default=datetime.date(2021, 12, 30), primary_key=True, serialize=False),
        ),
    ]
