# Generated by Django 3.2.9 on 2021-12-30 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridt_site', '0005_alter_application_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 15, 25, 30, 533156)),
        ),
    ]
