# Generated by Django 3.2.9 on 2021-12-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridt_site', '0006_alter_application_creation_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
