# Generated by Django 3.2.9 on 2021-12-30 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('value', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('usage_count', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('trial_period', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='RU', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
            ],
            options={
                'unique_together': {('currency', 'price')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2021, 12, 30, 15, 25, 30, 531969))),
                ('mail', models.EmailField(max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=20)),
                ('app_id', models.CharField(max_length=20)),
                ('next_payment_date', models.DateField(default=datetime.date(2021, 12, 30))),
                ('price', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ridt.price')),
                ('promo_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ridt.promocode')),
            ],
            options={
                'unique_together': {('creation_time', 'mail')},
            },
        ),
    ]
