# Generated by Django 3.2.9 on 2022-01-05 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 14, 5, 15, 653581)),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_payment_date',
            field=models.DateField(default=datetime.date(2022, 1, 5)),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='value',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
