# Generated by Django 3.2.9 on 2022-01-05 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridt', '0002_auto_20220105_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 14, 54, 29, 901423)),
        ),
    ]
