# Generated by Django 3.2.9 on 2022-01-05 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridt', '0003_alter_application_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 14, 55, 33, 755125)),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='value',
            field=models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
