# Generated by Django 3.2.9 on 2022-01-06 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridt', '0005_auto_20220105_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 18, 2, 37, 395873)),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 18, 2, 37, 395929)),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='trial_period',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_count',
            field=models.IntegerField(default=1),
        ),
    ]
