# Generated by Django 3.2.9 on 2022-01-06 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridt', '0006_auto_20220106_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 18, 15, 12, 515155)),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 18, 15, 12, 515211)),
        ),
    ]
